basePath: /
definitions:
  api_auth.ResetPasswordStruct:
    properties:
      password:
        type: string
      password_confirm:
        type: string
    required:
    - password
    - password_confirm
    type: object
  api_auth.SignIn:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  api_auth.SignUp:
    properties:
      email:
        type: string
      password:
        type: string
      password_confirm:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - password_confirm
    - username
    type: object
  api_auth.SignUpResponse:
    properties:
      expires_at:
        type: string
      expires_in:
        type: integer
      token:
        type: string
      user_id:
        type: integer
    type: object
  api_auth.TokenInfo:
    properties:
      expires_at:
        type: string
      expires_in:
        type: integer
      token:
        type: string
    type: object
  api_error.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: string
    type: object
  api_error.ValidationErrorResponse:
    properties:
      code:
        type: integer
      failed_fields:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
      status:
        type: string
    type: object
  auth.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      expires_in:
        type: integer
      group_id:
        type: integer
      id:
        type: integer
      role:
        type: string
      username:
        type: string
    type: object
  groups.CreateAction:
    properties:
      method:
        $ref: '#/definitions/permission.Method'
      resource:
        type: string
    required:
    - method
    - resource
    type: object
  groups.CreateGroup:
    properties:
      name:
        type: string
      permissions:
        items:
          $ref: '#/definitions/groups.CreatePermission'
        type: array
    required:
    - name
    - permissions
    type: object
  groups.CreatePermission:
    properties:
      actions:
        items:
          $ref: '#/definitions/groups.CreateAction'
        type: array
      name:
        type: string
    required:
    - actions
    - name
    type: object
  groups.ListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/groups.ResponseGroup'
        type: array
      page:
        type: integer
      page_size:
        type: integer
      total_count:
        type: integer
    type: object
  groups.ResponseAction:
    properties:
      method:
        $ref: '#/definitions/permission.Method'
      resource:
        type: string
    type: object
  groups.ResponseGroup:
    properties:
      actions:
        items:
          $ref: '#/definitions/groups.ResponseAction'
        type: array
      id:
        type: integer
      name:
        type: string
    type: object
  groups.UpdateGroup:
    properties:
      name:
        type: string
      permissions:
        items:
          $ref: '#/definitions/groups.CreatePermission'
        type: array
    type: object
  permission.Method:
    enum:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    type: string
    x-enum-varnames:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  utils.StatusResponse:
    properties:
      status:
        type: boolean
    type: object
host: localhost:9090
info:
  contact:
    email: miniyu97@gmail.com
    name: miniyus
    url: https://miniyus.github.io
  description: keyword-search-backend API
  license:
    name: MIT
  title: keyword-search-backend Swagger API Documentation
  version: 1.0.0
paths:
  /api/auth/me:
    get:
      consumes:
      - application/json
      description: get login user info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.User'
      security:
      - BearerAuth: []
      summary: get my info
      tags:
      - Auth
  /api/auth/password:
    patch:
      consumes:
      - application/json
      description: reset login user's password
      parameters:
      - description: reset password body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_auth.ResetPasswordStruct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: reset password
      tags:
      - Auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: sign up
      parameters:
      - description: sign up body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_auth.SignUp'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api_auth.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_error.ErrorResponse'
      summary: Sign up
      tags:
      - Auth
  /api/auth/revoke:
    delete:
      consumes:
      - application/json
      description: revoke current jwt token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.StatusResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api_error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: revoke token
      tags:
      - Auth
  /api/auth/token:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: login  body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_auth.SignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_auth.TokenInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_error.ErrorResponse'
      summary: login
      tags:
      - Auth
  /api/groups:
    get:
      consumes:
      - application/json
      description: get all group
      parameters:
      - description: page number
        in: query
        name: page
        required: true
        type: integer
      - description: page size
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/groups.ListResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api_error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: get all groups
      tags:
      - Groups
    post:
      consumes:
      - application/json
      description: create group
      parameters:
      - description: creat group
        in: body
        name: request
        schema:
          $ref: '#/definitions/groups.CreateGroup'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/groups.ResponseGroup'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_error.ValidationErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api_error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: create group
      tags:
      - Groups
    put:
      consumes:
      - application/json
      description: update group
      parameters:
      - description: group pk
        in: path
        name: id
        required: true
        type: integer
      - description: creat group
        in: body
        name: request
        schema:
          $ref: '#/definitions/groups.UpdateGroup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/groups.ResponseGroup'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_error.ValidationErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api_error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: update group
      tags:
      - Groups
  /api/groups/{id}:
    delete:
      consumes:
      - application/json
      description: delete group
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: bool
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api_error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: delete group
      tags:
      - Groups
    get:
      consumes:
      - application/json
      description: get group by pk
      parameters:
      - description: pk
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/groups.ResponseGroup'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api_error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: get group by pk
      tags:
      - Groups
  /api/groups/name/{name}:
    get:
      consumes:
      - application/json
      description: get group by name
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/groups.ResponseGroup'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api_error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: get group by name
      tags:
      - Groups
  /health-check:
    get:
      consumes:
      - '*/*'
      description: health check your server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.StatusResponse'
      summary: health check your server
      tags:
      - HealthCheck
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: Bearer token type
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
